const goodslist = {
  "message": {
    "total": 10,
    "pagenum": 1,
    "goods": [{
        "goods_id": 57434,
        "cat_id": 9,
        "goods_name": "创维（Skyworth）65V9E 65英寸25核4K HDR高清智能电视",
        "goods_price": 6499,
        "goods_number": 100,
        "goods_weight": 100,
        "goods_big_logo": "",
        "goods_small_logo": "",
        "add_time": 1516663280,
        "upd_time": 1516663280,
        "hot_mumber": 0,
        "is_promote": false,
        "cat_one_id": 1,
        "cat_two_id": 3,
        "cat_three_id": 9
      }, {
        "goods_id": 57194,
        "cat_id": 992,
        "goods_name": "亿力洗车工具汽车美容用品海绵刷不伤车漆擦车海绵清洁海绵",
        "goods_price": 29,
        "goods_number": 100,
        "goods_weight": 100,
        "goods_big_logo": "",
        "goods_small_logo": "",
        "add_time": 1516663280,
        "upd_time": 1516663280,
        "hot_mumber": 0,
        "is_promote": false,
        "cat_one_id": 962,
        "cat_two_id": 980,
        "cat_three_id": 992
      }, {
        "goods_id": 57445,
        "cat_id": 9,
        "goods_name": "创维（Skyworth）65V9E 65英寸25核4K HDR高清智能电视",
        "goods_price": 6499,
        "goods_number": 100,
        "goods_weight": 100,
        "goods_big_logo": "",
        "goods_small_logo": "",
        "add_time": 1516663280,
        "upd_time": 1516663280,
        "hot_mumber": 0,
        "is_promote": false,
        "cat_one_id": 1,
        "cat_two_id": 3,
        "cat_three_id": 9
      },
      {
        "goods_id": 57332,
        "cat_id": 998,
        "goods_name": "400毫升 海鲜食品冷藏冰包 注水冰袋医用冰袋户外冷藏保鲜熟食冷藏（10个装）",
        "goods_price": 14,
        "goods_number": 100,
        "goods_weight": 100,
        "goods_big_logo": "",
        "goods_small_logo": "",
        "add_time": 1516663280,
        "upd_time": 1516663280,
        "hot_mumber": 0,
        "is_promote": false,
        "cat_one_id": 962,
        "cat_two_id": 981,
        "cat_three_id": 998
      },
      {
        "goods_id": 57434,
        "cat_id": 9,
        "goods_name": "创维（Skyworth）65V9E 65英寸25核4K HDR高清智能电视",
        "goods_price": 6499,
        "goods_number": 100,
        "goods_weight": 100,
        "goods_big_logo": "",
        "goods_small_logo": "",
        "add_time": 1516663280,
        "upd_time": 1516663280,
        "hot_mumber": 0,
        "is_promote": false,
        "cat_one_id": 1,
        "cat_two_id": 3,
        "cat_three_id": 9
      },
      {
        "goods_id": 57194,
        "cat_id": 992,
        "goods_name": "亿力洗车工具汽车美容用品海绵刷不伤车漆擦车海绵清洁海绵",
        "goods_price": 29,
        "goods_number": 100,
        "goods_weight": 100,
        "goods_big_logo": "",
        "goods_small_logo": "",
        "add_time": 1516663280,
        "upd_time": 1516663280,
        "hot_mumber": 0,
        "is_promote": false,
        "cat_one_id": 962,
        "cat_two_id": 980,
        "cat_three_id": 992
      }, {
        "goods_id": 57356,
        "cat_id": 998,
        "goods_name": "400毫升 海鲜食品冷藏冰包 注水冰袋医用冰袋户外冷藏保鲜熟食冷藏（10个装）",
        "goods_price": 14,
        "goods_number": 100,
        "goods_weight": 100,
        "goods_big_logo": "",
        "goods_small_logo": "",
        "add_time": 1516663280,
        "upd_time": 1516663280,
        "hot_mumber": 0,
        "is_promote": false,
        "cat_one_id": 962,
        "cat_two_id": 981,
        "cat_three_id": 998
      },
      {
        "goods_id": 57454,
        "cat_id": 9,
        "goods_name": "创维（Skyworth）65V9E 65英寸25核4K HDR高清智能电视",
        "goods_price": 6499,
        "goods_number": 100,
        "goods_weight": 100,
        "goods_big_logo": "",
        "goods_small_logo": "",
        "add_time": 1516663280,
        "upd_time": 1516663280,
        "hot_mumber": 0,
        "is_promote": false,
        "cat_one_id": 1,
        "cat_two_id": 3,
        "cat_three_id": 9
      }
    ]
  },
  "meta": {
    "msg": "获取成功",
    "status": 200
  }
}
export default goodslist
